<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="sg.aspx.cs" Inherits="collegemanegement.sg" %>

<%@ Register assembly="DevExpress.Web.v15.2, Version=15.2.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>gallery</title>
    <style>
        #sg
        {    position:relative;
             top:449px;
             height:100px;
             width:1450px;
             background:#1E61A8;
            
        }
        #usg
        {
            font-size:40px;
            color:white;
            position:relative;
            top:-100px;
            left:260px;
        }
        .auto-style1
        {
            width: 100%;
        }
        #link
        {
            position:relative;
            top:-400px;
            color:red;

        }
    </style>
</head>
<body background-color:"#0000ff">
    <form id="form1" runat="server">
    <div id="sg">&nbsp;<table class="auto-style1">
        <tr>
            <td>
                &nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
        </table>
      <p id="usg" > USHA MARTIN ACADEMY DHANBAD GALLERY</p>
        </div>
    <div>
    
    </div>
        <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ImageSourceFolder="~/properties" style="top: 15px; left: 11px; position: absolute; width: 1417px; height: 491px;">
            <SettingsImageArea AnimationType="Fade" NavigationDirection="Vertical" />
            <SettingsNavigationBar Position="Left" />
            <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
        </dx:ASPxImageSlider>
    </form>
    <div id="link"><a href="home.aspx">back</a></div>
</body>
</html>
